schema_version: 1

context:
  name: "wilson"
  version: "2.5.2"
  # Should be Python 3.7, but rundec is Python 3.9+ on conda-forge
  python_min: "3.9"

package:
  name: ${{ name|lower }}
  version: ${{ version }}

source:
  url: https://pypi.org/packages/source/${{ name[0] }}/${{ name }}/wilson-${{ version }}.tar.gz
  sha256: deee9fc0d3dad5ad23b60a87ccc22049c5e1d36abdd2413b5e22029b5f1f3cbf

build:
  noarch: python
  number: 0
  script: ${{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  python:
    entry_points:
      - wcxf = wilson.wcxf.cli:wcxf_cli
      - wcxf2eos = wilson.wcxf.cli:eos
      - wcxf2dsixtools = wilson.wcxf.cli:wcxf2dsixtools
      - dsixtools2wcxf = wilson.wcxf.cli:dsixtools2wcxf
      - wcxf2smeftsim = wilson.wcxf.cli:smeftsim

requirements:
  host:
    - python ${{ python_min }}.*
    - setuptools
    - pip
  run:
    - python >=${{ python_min }}
    - numpy >=1.16.5
    - scipy >=1.0
    - pandas
    - pylha >=0.2
    - pyyaml
    - ckmutil >=1.2.0
    - rundec >=0.5
    - voluptuous

tests:
  - python:
      imports:
        - wilson
      pip_check: true
      python_version: ${{ python_min }}.*
  - requirements:
      run:
        - python ${{ python_min }}.*
        - pip
    script:
      - pip list
      - wcxf --help
      - wcxf2eos --help
      - wcxf2dsixtools --help
      - dsixtools2wcxf --help
      - wcxf2smeftsim --help

about:
  homepage: https://github.com/wilson-eft/wilson
  summary: Toolkit for effective field theories beyond the Standard Model
  license: MIT
  license_file: LICENSE
  repository: https://github.com/wilson-eft/wilson
  documentation: https://wilson-eft.github.io/

extra:
  recipe-maintainers:
    - matthewfeickert
